blog/user/views.py
from flask import Blueprint, render_template, redirect, url_for, request
from werkzeug.exceptions import NotFound
from blog.models import User
from flask_login import login_required, current_user, login_user
from blog.forms.user import UserRegisterForm
from werkzeug.security import generate_password_hash
from blog.models.database import db


user = Blueprint("users", __name__, url_prefix='/users', static_folder='../static')


@user.route('register', methods=['GET','POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('users.profile', pk=current_user.id))
    
    form = UserRegisterForm(request.form)
    
    errors = []
    if request.method == 'POST' and form.validate_on_submit():
        if User.query.filter_by(email=form.email.data).count():
            form.email.errors.append('email already exists')
            return render_template('users/register.html', form=form)

        _user = User(
            username=form.username.data,
            email=form.email.data,
            first_name=form.first_name.data,
            last_name=form.last_name.data,
            password=generate_password_hash(form.password.data),
        )

        db.session.add(_user)
        db.session.commit()

        login_user(_user)

    return render_template(
        'users/register.html',
        form=form,
        errors=errors,
    )

@user.route('/', endpoint="list")
def user_list():
    users = User.query.all()
    return render_template(
        'users/list.html',
        users=users,
    )


@user.route('/<int:pk>')
@login_required
def profile(pk: int):
    selected_user = User.query.filter_by(id=pk).one_or_none()
    if not selected_user:
        raise NotFound(f"User #{pk} doesn't exist!")

    return render_template(
        'users/details.html',
        user=selected_user,
    )

blog/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    {% block css %}
    <!-- Bootstrap CSS -->
    <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">
    {% endblock %}

    <title>
        {% block title %} My app - {% endblock %}
    </title>
</head>

<body>
    {% include 'navbar.html' %}
    <div class="container">
        {% block body %} {% endblock %}
    </div>

    {% block js %}


    {% endblock %}

</body>

</html>

blog/templates/index.html
{% extends 'base.html' %}

{% block title %}
{{ super() }}
Main page
{% endblock %}


{% block body %}
<h1>
    Hello
    {% if current_user.is_authenticated %}
    {{ current_user.username }}
    {% else %}
    anon
    {% endif %}
</h1>
{% endblock %}

blog/templates/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{{url_for('index.index')}}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{url_for('users.list')}}">Users</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{url_for('authors.list')}}">Authors</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{url_for('articles_app.list')}}">Articles</a>
        </li>
        {% if current_user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{{url_for('articles_app.create')}}">Create articles</a>
        </li>
        <li>
          <a class="nav-link" href="{{ url_for('auth.logout') }}">Logout</a>
          {% else %}
          <a href="{{ url_for('auth.login') }}" class="nav-link {% if request.endpoint == 'login' -%}active{%- endif %}">
            Login
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{url_for('users.register')}}">Registration</a>
        </li>
        {% endif %}
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>