blog/forms/article.py
from flask_wtf import FlaskForm
from wtforms import StringField, validators, SubmitField, TextAreaField, SelectMultipleField

class CreateArticleForm(FlaskForm):
  title = StringField("Title", [validators.DataRequired()])
  text = TextAreaField("Text", [validators.DataRequired()])
  tags = SelectMultipleField('Tags', coerce=int)
  submit = SubmitField('Create')

blog/articles/views.py
from flask import Blueprint, render_template, request, redirect, url_for
from werkzeug.exceptions import NotFound
from blog.models.models import Article, Author, Tag
from blog.forms.article import CreateArticleForm
from flask_login import login_required, current_user
from blog.models.database import db
from sqlalchemy.orm import joinedload


articles_app = Blueprint("articles_app", __name__, url_prefix='/articles', static_folder='../static')

@articles_app.route("/", methods=['GET'], endpoint="list")
@login_required
def articles_list():
    _articles = Article.query.all()
   
    return render_template(
        'articles/list.html',
        articles=_articles,
    )


@articles_app.route("/<int:pk>/", methods=['GET'])
@login_required
def get_articles(pk: int):
    _article: Article = Article.query.filter_by(article_id=pk).options(
joinedload(Article.tags)).one_or_none()

    if _article is None:
        raise NotFound(f"Article #{pk} doesn't exist!")
    return render_template('articles/details.html', articles_app=_article)


@articles_app.route('/create/', methods=['GET'])
@login_required
def create_article_form():
    form = CreateArticleForm(request.form)
    form.tags.choices = [(tag.id, tag.name) for tag in Tag.query.order_by('name')]
    return render_template('articles/create.html', form=form)

@articles_app.route("/create/", methods=['POST'], endpoint="create")
@login_required
def create_article():
    form = CreateArticleForm(request.form)

    form.tags.choices = [(tag.id, tag.name) for tag in Tag.query.order_by('name')]

    if form.validate_on_submit():
        _article = Article(title=form.title.data.strip(), text=form.text.data)

        if current_user.authors:
            _article.author_id = current_user.authors.id
        else:
            author = Author(user_id=current_user.id)
            db.session.add(author)
            db.session.flush()
            _article.author_id = author.id
        
        if form.tags.data:
            selected_tags = Tag.query.filter(Tag.id.in_(form.tags.data))
            for tag in selected_tags:
                _article.tags.append(tag)

        db.session.add(_article)
        db.session.commit()

        return redirect(url_for('articles_app.get_articles', pk=_article.article_id))
    
    return render_template('articles/create.html', form=form)


@articles_app.route("/tag/<int:pk>/", methods=['GET'])
@login_required
def get_articles_by_tag(pk: int):
    article = Article.query.join(Article.tags).filter(Tag.id==pk)
    print(article)
    if article is None:
        raise NotFound(f"Article #{pk} doesn't exist!")
    return render_template('articles/tags.html', articles_app=article)

blog/templates/articles/create.html
{% extends 'base.html' %}
{% from "macro/formhelpers.html" import render_field %}

{% block title %}
Create article
{% endblock %}

{% block body %}
{% if errors %}
{% for error in errors %}
<div class="alert alert-danger" role="alert">
    {{ error }}
</div>
{% endfor %}
{% endif %}

<form method="POST">
    {{ form.csrf_token }}
    {% for field in ['title', 'text', 'tags'] %}
    {{ render_field(form[field]) }}
    {% endfor %}

    {{ form.submit(class="btn btn-primary mb-3") }}
</form>
{% endblock %}s

blog/templates/articles/details.html
{% extends './base.html' %}

{% block title %}
Article {{ articles_app.id }}: {{ articles_app.title }}
{% endblock %}

{% block body %}
<div>
    <a href="{{ url_for('articles_app.list') }}">Back to articles list</a>
</div>
<h1>{{ articles_app.title }}</h1>
<div class="row">
    <div class="col-md-12">{{ articles_app.text }}</div>
</div>
<div class="row">
    <div class="col-6">
        <div><small class="text-muted"></small>Author: {{ articles_app.author.user.first_name}} {{ articles_app.author.user.last_name}}</small></div>
        <div><small class="text-muted">{{ articles_app.created}}</small></div>
        <div><small class="text-muted">{{ articles_app.updated}}</small></div>
    </div>
    <!-- .strftime('%d-%m-%Y %H:%M:%S') -->
    <div class="col-6">
        {% for tag in articles_app.tags %}
        <span class="badge bg-light text-dark"><a href="{{ url_for('articles_app.get_articles_by_tag', pk=tag.id) }}">{{ tag.name }}</a></span>
        {% endfor %}
    </div>
</div>
{% endblock %}

blog/templates/articles/list.html
{% extends 'base.html' %}

{% block title %}
Articles list
{% endblock %}

{% block body %}
<div class="container text-center">
    <div class="row">
        <div class="col">
            <h1>Articles</h1>
            {% for article in articles %}
            <ul>
                <li>
                    <a href="{{ url_for('articles_app.get_articles', pk=article.article_id) }}">
                        {{ article.title -}}
                    </a>
                </li>
            </ul>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

blog/templates/articles/tags.html
{% extends 'base.html' %}

{% block title %}
Articles list
{% endblock %}

{% block body %}

<div class="container-fluid">
    <div class="row">
        <div class="col">
            <h1>Статьи по тэгу</h1>
        </div>

        <div class="list-group">
            {% for article in articles_app %}
            <a href="{{ url_for('articles_app.get_articles', pk=article.article_id) }}" class="list-group-item list-group-item-action " aria-current="true">
                <div class="d-flex w-100 justify-content-between">
                    <h5 class="mb-1">{{ article.title -}}</h5>
                    <h5 class="mb-1">{{ article.tags.name}}</h5>
                    <small>{{ article.created}}</small>
                </div>
            </a>
            <br>
            {% endfor %}
        </div>
    </div>
    {% endblock %}