blog/forms/article.py
from flask_wtf import FlaskForm
from wtforms import StringField, validators, SubmitField, TextAreaField, SelectMultipleField

class CreateArticleForm(FlaskForm):
  title = StringField("Title", [validators.DataRequired()])
  text = TextAreaField("Text", [validators.DataRequired()])
  tags = SelectMultipleField('Tags', coerce=int)
  submit = SubmitField('Create')

blog/articles/views.py
from flask import Blueprint, render_template, request, redirect, url_for
from werkzeug.exceptions import NotFound
from blog.models.models import Article, Author, Tag
from blog.forms.article import CreateArticleForm
from flask_login import login_required, current_user
from blog.models.database import db
from sqlalchemy.orm import joinedload


articles_app = Blueprint("articles_app", __name__, url_prefix='/articles', static_folder='../static')

@articles_app.route("/", methods=['GET'], endpoint="list")
@login_required
def articles_list():
    _articles = Article.query.all()
   
    return render_template(
        'articles/list.html',
        articles=_articles,
    )


@articles_app.route("/<int:pk>/", methods=['GET'])
@login_required
def get_articles(pk: int):
    _article: Article = Article.query.filter_by(article_id=pk).options(
joinedload(Article.tags)).one_or_none()

    if _article is None:
        raise NotFound(f"Article #{pk} doesn't exist!")
    return render_template('articles/details.html', articles_app=_article)


@articles_app.route('/create/', methods=['GET'])
@login_required
def create_article_form():
    form = CreateArticleForm(request.form)
    form.tags.choices = [(tag.id, tag.name) for tag in Tag.query.order_by('name')]
    return render_template('articles/create.html', form=form)

@articles_app.route("/create/", methods=['POST'], endpoint="create")
@login_required
def create_article():
    form = CreateArticleForm(request.form)

    form.tags.choices = [(tag.id, tag.name) for tag in Tag.query.order_by('name')]

    if form.validate_on_submit():
        _article = Article(title=form.title.data.strip(), text=form.text.data)

        if current_user.authors:
            _article.author_id = current_user.authors.id
        else:
            author = Author(user_id=current_user.id)
            db.session.add(author)
            db.session.flush()
            _article.author_id = author.id
        
        if form.tags.data:
            selected_tags = Tag.query.filter(Tag.id.in_(form.tags.data))
            for tag in selected_tags:
                _article.tags.append(tag)

        db.session.add(_article)
        db.session.commit()

        return redirect(url_for('articles_app.get_articles', pk=_article.article_id))
    
    return render_template('articles/create.html', form=form)


@articles_app.route("/tag/<int:pk>/", methods=['GET'])
@login_required
def get_articles_by_tag(pk: int):
    article = Article.query.join(Article.tags).filter(Tag.id==pk)
    print(article)
    if article is None:
        raise NotFound(f"Article #{pk} doesn't exist!")
    return render_template('articles/tags.html', articles_app=article)

blog/authors/views.py
from flask import Blueprint, render_template
from blog.models.models import Author, Article
from flask_login import login_required
from werkzeug.exceptions import NotFound


author = Blueprint("authors", __name__, url_prefix='/authors', static_folder='../static')

@author.route('/', endpoint="list")
def author_list():
    authors = Author.query.all()
    return render_template(
        'authors/list.html',
        authors=authors,
    )

@author.route('/articles/<int:pk>', methods=['GET'])
@login_required
def get_articles_by_author(pk: int):
    _article = Article.query.join(Author.articles).filter(Author.id==pk)
    if _article is None:
        raise NotFound(f"Article #{pk} doesn't exist!")
    return render_template('authors/articles.html', author=_article)

blog/templates/authors/articles.html
{% extends 'base.html' %}

{% block title %}
Articles list by author
{% endblock %}

{% block body %}

<div class="container-fluid">
    <div class="row">
        <div class="col">
            <h1>Статьи автора {{ author.first_name}}</h1>
        </div>

        <div class="list-group">
            {% for article in author %}
            <a href="{{ url_for('articles_app.get_articles', pk=article.article_id) }}" class="list-group-item list-group-item-action " aria-current="true">
                <div class="d-flex w-100 justify-content-between">
                    <h5 class="mb-1">{{ article.title -}}</h5>
                    <h5 class="mb-1">{{ article.tags.name}}</h5>
                    <small>{{ article.created}}</small>
                </div>
            </a>
            <br>
            {% endfor %}
        </div>
    </div>

    {% endblock %}

blog/templates/authors/list.html
{% extends 'base.html' %}

{% block title %}
{{ super() }}
Author list
{% endblock %}


{% block body %}
<div class="container text-center">
    <div class="row">
        {% for author in authors %}
        <div class="col-md-4">
            <div class="card user-card" style="width: 20rem;">
                <div class="card-header">
                    <h5>Profile</h5>
                </div>
                <div class="card-block">
                    <div class="user-image">
                        <img src="https://bootdey.com/img/Content/avatar/avatar7.png" class="img-radius" alt="User-Profile-Image">
                    </div>
                    <h6 class="f-w-600 m-t-25 m-b-10">{{ author.user.first_name }} {{ author.user.last_name }}</h6>
                    <a href="">
                        <a href="{{ url_for('authors.get_articles_by_author', pk=author.id)}}">
                            <h6 class="f-w-600 m-t-25 m-b-10">Cтатьи</h6>
                        </a>
                    </a>
                    <hr>
                    <div class="row justify-content-center user-social-link">
                        <div class="col-auto"><a href="#!"><i class="fa fa-facebook text-facebook"></i></a></div>
                        <div class="col-auto"><a href="#!"><i class="fa fa-twitter text-twitter"></i></a></div>
                        <div class="col-auto"><a href="#!"><i class="fa fa-dribbble text-dribbble"></i></a></div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}